services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: etl
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl -d etl"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: etl
      DB_USER: etl
      DB_PASSWORD: etl
    volumes:
      - .:/app
    command: ["python", "etl_consumer_complaints.py"]

volumes:
  pgdata:
